sudo: required

language: python

env:
  - SERVER_USER=admin SERVER_PASSWD=admin

services:
  - docker

install:
  - docker build -t cetres/openshift-pentaho .
  - docker run -d -p 127.0.0.1:8080:8080 --name pdi cetres/openshift-pentaho
  - sleep 60
  - docker logs pdi

before_script:
  - pip install -r tests/requirements.txt

script:
  - docker ps | grep -q pdi
  - python tests/run_tests.py
